# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Install node dependencies, add assets and deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm dependencies
      run: docker run --rm -v $(pwd):/app -w /app node:19.6.0-alpine npm install --silent

    - name: Build assets
      run: docker run --rm -v $(pwd):/app -w /app node:19.6.0-alpine npm run build --silent

    - name: Clean up
      run: |
        sudo rm -rf /node_modules
        sudo rm -rf /package-lock.json
        sudo rm -rf /package.json
        sudo rm -rf /webpack-config.js
        sudo rm -rf /src
