name: Install node dependencies, add assets and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm dependencies
      run: docker run --rm -v $(pwd):/app -w /app node:19.6.0-alpine npm install --silent

    - name: Build assets
      run: docker run --rm -v $(pwd):/app -w /app node:19.6.0-alpine npm run build --silent

    - name: Clean up
      run: |
        sudo rm -rf $GITHUB_WORKSPACE/node_modules
        sudo rm -rf $GITHUB_WORKSPACE/package-lock.json
        sudo rm -rf $GITHUB_WORKSPACE/package.json
        sudo rm -rf $GITHUB_WORKSPACE/webpack-config.js
        sudo rm -rf $GITHUB_WORKSPACE/src

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist


